### ISSUE TITLE
[feature] Integration with Home Assistant

### ISSUE THREAD

**Issue by jackbrown1993** [jackbrown1993/Jacuzzi-RS485#46]
Already started this in #39

**Comment by jackbrown1993** [comment]
@HyperActiveJ I see you started on something similar, are you ok if I have a poke around with your obsolete repo (https://github.com/HyperActiveJ/SundanceJacuzzi_HomeAssistant_TCP_RS485) and copy some of the code?

Conscious we have a few different repos covering various models and use cases so trying to bring everything together under this one repo which I am happy for everyone to contribute to.

**Comment by HyperActiveJ** [comment]
Go for it! I was running as a home assistant intergration initally, but I don't have time to keep up with the home assistant internal changes that kept breaking it. It was also harder to debug. I found having a stand alone mqtt to spa app instance instead was less work to maintain. I was also able to run it on a device closer to the spa latency wiae which helped with occasional corrupted bus issues.

**Comment by jackbrown1993** [comment]
@HyperActiveJ started to look at this again, MQTT auto discovery seems to work pretty well! See the pull I am about to tag below.
